name: CI - Explainability ML

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: "true"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install papermill nbconvert nbformat
        pip install eli5

    - name: Execute all notebooks
      run: |
        for nb in notebooks/*.ipynb; do
            echo "Executando $nb"
            papermill "$nb" "${nb%.ipynb}_out.ipynb"
        done

    - name: Generate VERSION file
      run: |
        python scripts/write_version.py

    - name: Upload CI artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ci-artifacts
        path: |
          VERSION
          notebooks/*_out.ipynb
